---
version: "3.8"

networks:
  # swag_proxy:
  #   external: true
  backend:

services:
  phoenix:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phoenix
    environment:
      - TZ=Europe/Berlin
      - PORT=4000
      - DATABASE_URL=postgresql://user:password@postgres:5432/database
      - SECRET_KEY_BASE=LCEMBgp+TUlWBtjPa5Gf4gOum+8X4UNQjmlT62Od7gsLmKr76aXY9AXm825CRFht
    ports:
      - 4000:4000
    depends_on:
      - "postgres"
    networks:
      # - swag_proxy
      - backend
    restart: unless-stopped
  postgres:
    image: postgres:15.1-alpine3.17
    container_name: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - backend
    restart: unless-stopped
